# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

sudo: false # route your build to the container-based infrastructure for a faster build
language: java
install: true
jdk:
  - openjdk11

script:
  - ./mvnw clean install -X checkstyle:check

deploy:
  - provider: releases
    api_key:
      secure: "YtK6gh4f6ax5JITgE6N3SIZUN3gzCp3meLfzWtRJmRlntU5VOQYnwzsL7CeVMxm/A+5uIalSRNrc+AqYpOYphmNYz2BDnEQDocKXugkbpH2N7FVGNBS8EXu7ZC2MR/0/sy1E43+trReFdPsNWx5kM04SsQB61aA2StwESSWz7x5ZbU2qk+d1N5NWa3qDo1Mig9N/6qdkvef8y+XavbQus9F9cGUdspminmriFgg9x4otkHD+9f5YhfITpf0Zt00XO/wRkckFTh1un8B56dTJ7JVnMatwM+HGydSZ3KNquZobT400V8nnO3a2CsjzjhSSULklv9ASzVv5D5p6oZpAuUOlIIqsVQzxCdLq/qRJCgjvphmAsX5MBzE9sRqaK+HLXcN2Bs0sQzj7tozQgECBv/9dUrQ7F/wvegNI6HqLHF66YmR+JMpFGab1RlvqZ+SKB7TwY67kdZkHJxaxfjc0/y7IO0Fdiigw8qQNfTSQ+oRPyGMwGKnMDeNHKeJ67LWNGjyjprG/Ywh6zgwEYnAIiwEncOMhdRGSobKqeYU3o4uOGD7zLnMC2pLtPhi+ymj4tEOjmpNmtZn69Q6J177i4cVJNjYPXuXVcwM/JxmxZU7u0XwomV6LVkWQKx9qmwET0gT1uX1sxC1IPmQA/77uKQNqFGRydm/rCHcO5lEe1Kc="
    file_glob: true
    file:
      - "target/rocket-chat-exporter-*.jar"
      - "target/*.sha256"
      - "target/checksum-sha256.txt"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: "oOm/y7uIrNl//7SukIvAs+hTPwnG8+9e7GplMhFspMvHwin5sYiMp1yFXcXFd+VSPFASktyQLzUjrx9BSoT3pupIISI9D62SdzVsCXDKX2HLFHWRI9QVo9lc4dmc3+w64tvBjIomY/Cs/EKJ0QWUlEH3kA2YE40IZFPCQIPnHqLpw4jvsGBHVTc99RddchWSH6r2QzknUZjeSJEPzgWJmCaKlGt8NP9JgFq85/q5ZSsEA8YFr8BJ/eo9HcStw3Pq2e6gyVHTkmn5ML+Q1OP469bif5+0RyFXyLkZ9qQFSPqzMpoYqyxQ5u73UjvdXEFbx0dKNo12wgKh5gm5wx3NiHDF0VfllmMSUmU4qw9F/7makM0pMnhsujCkL27p68/OVZy7jGpwIacx8wxsnf9nWSz/ZkWabaeTFhZEL/1mIdbrlpvDrAngc2OBrF7wANVdwJsYxix/31s0DxW7FA/u1/Gk40kKzN21WfbbQavF2yUkOJ0waTj45EDuQIz5YXOJIKDC5haY+1PR5Phw3F/JOvRdNXUzAkzUSctKkCkZJ0d5Bg2pJZx6davkHc9VJMP59J3nXzCVZBKDbrnZ+QA0M1UemG4CaoOpd3RvKWS4gdBSH/Cxzn3qfZgDgolHa7pfUP6XnIt4Sbd04PzJQCshcgb3XV9dn/3dZ8BIvarySKo="
  email: false
