# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

sudo: false # route your build to the container-based infrastructure for a faster build
language: java
install: true
jdk:
  - openjdk11

script:
  - ./mvnw clean install checkstyle:check

after_success:
  - ./mvnw test jacoco:report coveralls:report

deploy:
  - provider: releases
    api_key:
      secure: "M32tO++Lpt12pwdujRuYqcm7d6O9zIOeRZSz1F4Ps/c5lcryQdtV6USNfOFY3xYDU5Lg01Wwn2yTUAZGLG0Crb/+BfKtF+s39mIh54uUMwE1eDs8X7VsmAec3EX3iqTHPZha/LrcooAY/DT2p40SYbOkfkIQRIFJReO89nD7mDnge/upzfPHW8FeL/yddg0zKXRXpCyNKURhBg/hnfYhamOMOzc5u0bYhGWKRKBg88//eFnMqT4VwMEWQPXHDJ+dLEWn6sLFnzZaOJBlSsdwKoudJ+mTyxmZQWK0ArDR7uoxrJb3ypZb13EBVSCLoA07gkMBfbf7HueSMwBJgWbq44pTUav5lm2p/WmdA3yHHGKYN+/VnlAh9iiAyw+aJibWXtI+dCxvxm6Vt6pnMJ372vRyhKipiNZDUe9h7o+pM7VZO44WZdXQIM6Yn6zhkZASxAiJtqpsdwlWtiGu01BMnraKVXEG0BeEF63EaRMiS+4tAanI1UV+IIrupTdmCOjJqXlkjPK555qEipbqIgnS/E0aGn6ajZIVSThqQipigJfUeUMIHLeAjzEEJ+NP1sB1f6lZ9CoVu8gqySw+hY0SZir9Fw1drMYSbnVDkVJQKEbiJhauSj4utK1TStWJNRG6Vb5POkVnnp/xa1W4EkgFGtu+MVIiF6wrqf23JP1xpCw="
    file_glob: true
    file:
      - "target/rocketchat-exporter-*.jar"
      - "target/*.sha256"
      - "target/checksum-sha256.txt"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: "oOm/y7uIrNl//7SukIvAs+hTPwnG8+9e7GplMhFspMvHwin5sYiMp1yFXcXFd+VSPFASktyQLzUjrx9BSoT3pupIISI9D62SdzVsCXDKX2HLFHWRI9QVo9lc4dmc3+w64tvBjIomY/Cs/EKJ0QWUlEH3kA2YE40IZFPCQIPnHqLpw4jvsGBHVTc99RddchWSH6r2QzknUZjeSJEPzgWJmCaKlGt8NP9JgFq85/q5ZSsEA8YFr8BJ/eo9HcStw3Pq2e6gyVHTkmn5ML+Q1OP469bif5+0RyFXyLkZ9qQFSPqzMpoYqyxQ5u73UjvdXEFbx0dKNo12wgKh5gm5wx3NiHDF0VfllmMSUmU4qw9F/7makM0pMnhsujCkL27p68/OVZy7jGpwIacx8wxsnf9nWSz/ZkWabaeTFhZEL/1mIdbrlpvDrAngc2OBrF7wANVdwJsYxix/31s0DxW7FA/u1/Gk40kKzN21WfbbQavF2yUkOJ0waTj45EDuQIz5YXOJIKDC5haY+1PR5Phw3F/JOvRdNXUzAkzUSctKkCkZJ0d5Bg2pJZx6davkHc9VJMP59J3nXzCVZBKDbrnZ+QA0M1UemG4CaoOpd3RvKWS4gdBSH/Cxzn3qfZgDgolHa7pfUP6XnIt4Sbd04PzJQCshcgb3XV9dn/3dZ8BIvarySKo="
  email: false
